#!/usr/bin/env python
'''
Dump files from current directory as JSON-encoded list
'''
import subprocess as sp
import json
file_list = [x for x in sp.Popen(['ls'],stdout=sp.PIPE).communicate()[0].split('\n') if x]
print
print json.dumps(file_list)