#!/usr/bin/env python
'''	A script copied to throwup_server's destination folder
This URL (when server is running) serves information
based on post requests from the calling directory	
'''

import cgi
import subprocess as sp
import json

print

def bash(cmd, **shell):
	''' Issue subprocess calls from cmd (standard bash syntax)
		Determine whether cmd should be split (depending on whether shell=True)
		Print any error received and return the subprocess command's response	'''
	
	resp, err = sp.Popen(cmd if shell else cmd.split(' '), stdout=sp.PIPE, shell=shell).communicate()
	if err: 
		print 'Got error on command "%s":' % cmd
		print err
	return resp

def main():
	data = cgi.FieldStorage()['package'].value
	
	if data == 'pwd':
		pwd = bash('pwd')
		print json.dumps(pwd)
	

if __name__ == '__main__':
	main()